/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Instructor
 */

package folderzip;

import java.io.BufferedInputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    String Ruta7Zip;
    String RutaWinRar;
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFC_Carpeta = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTF_Dir = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtResultado = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        JFC_Carpeta.setDialogTitle("Seleccione la carpeta principal");
        JFC_Carpeta.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Carpeta:");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Extractor de Multiples Archivos Comprimidos");

        JTF_Dir.setEditable(false);

        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTxtResultado.setEditable(false);
        jTxtResultado.setColumns(20);
        jTxtResultado.setRows(5);
        jScrollPane1.setViewportView(jTxtResultado);

        jLabel3.setText("Resultado:");

        jButton2.setText("Extraer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(JTF_Dir, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addComponent(jLabel3))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTF_Dir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 20, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Mostramos un dialogo para seleccionar
        int returnVal = JFC_Carpeta.showOpenDialog(this);
        if (returnVal == JFC_Carpeta.APPROVE_OPTION) { //Se le dio aceptar al dialogo
            File file = JFC_Carpeta.getSelectedFile(); //Obtenemos la ruta seleccionada
            try {
                // Mostramos la ruta seleccionada en el text
                JTF_Dir.setText(file.getAbsolutePath());
            } catch (Exception ex) {
                System.out.println("Problemas al seleccionar la carpeta"+file.getAbsolutePath());
            }
        } else {
            System.out.println("Accion cancelada por el usuario");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        boolean exists7Zip = Verificar7Zip();
        boolean existsWinRar = VerificarWinRAR();
        
        if (exists7Zip || existsWinRar){
            boolean status7Zip, statusWinrar;
            File dir = new File(JTF_Dir.getText()); //Obtenemos la carpeta seleccionada
            String[] ficheros = dir.list(); //Obtenemos las subcarpetas
            if (ficheros == null) { //Si la carpeta esta vacia
                jTxtResultado.setText("No hay ficheros en el directorio especificado");
            } else {
                jTxtResultado.setText("Iniciando...");
                for (int x = 0; x < ficheros.length; x++) { //Recorremos las carpetas
                    String carpetaInterna = JTF_Dir.getText() + "\\" + ficheros[x]; //Ficheros internos
                    File dirInt = new File(carpetaInterna);
                    String[] ficInternos = dirInt.list();//Lista de archivos dentro de la subcarpeta

                    if (ficInternos != null) { //Si hay archivos dentro de la subcarpeta
                        String nameFile7Zip = "";
                        String nameFileWinrar = "";
                        for (int i = 0; i < ficInternos.length; i++) {//Recorremos los archivos
                            
                            if(exists7Zip){
                                int fileExist = ficInternos[i].indexOf(".7z.001");//Buscamos el primer 7zip
                                if(fileExist != -1) {//Verificamos si existe un archivo inicial 7zip
                                    jTxtResultado.setText(jTxtResultado.getText()+"\n"+"Descomprimendo "+carpetaInterna+"\\"+ficInternos[i]);
                                    status7Zip = Descompress7Zip(carpetaInterna, ficInternos[i]);
                                    if (status7Zip){
                                        nameFile7Zip = ficInternos[i];
                                        String[] parts = nameFile7Zip.split(".7z.");
                                        nameFile7Zip = parts[0];
                                    }
                                }
                            }
                            
                            if (existsWinRar) {
                                int fileExist = ficInternos[i].indexOf(".part1.rar");//Buscamos el primer 7zip
                                if (fileExist != -1) {//Verificamos si existe un archivo inicial Winrar
                                    jTxtResultado.setText(jTxtResultado.getText() + "\n" + "Descomprimendo " + carpetaInterna + "\\" + ficInternos[i]);
                                    statusWinrar = DescompressWinRAR(carpetaInterna, ficInternos[i]);
                                    if (statusWinrar) {
                                        nameFileWinrar = ficInternos[i];
                                        String[] parts = nameFileWinrar.split(".part1.");
                                        nameFileWinrar = parts[0];
                                    }
                                    
                                }
                            }
                        }
                        
                        if (!nameFile7Zip.equalsIgnoreCase("") || !nameFileWinrar.equalsIgnoreCase("")) {
                            jTxtResultado.setText(jTxtResultado.getText() + "\n" + "Eliminando Archivos...");
                            for (int i = 0; i < ficInternos.length; i++) {
                                if (ficInternos[i].indexOf(nameFile7Zip) != -1) {
                                    try {
                                        File fn = new File(carpetaInterna + "\\" + ficInternos[i]);
                                        fn.delete();
                                        jTxtResultado.setText(jTxtResultado.getText() + "\n" + "Archivo Eliminado " + ficInternos[i]);
                                        System.out.println("El fichero ha sido borrado satisfactoriamente = " + ficInternos[i]);
                                    } catch (Exception errFil) {
                                        System.err.println("El fichero no puede ser borrado: " + ficInternos[i] + " ");
                                        System.err.println(errFil);
                                    }
                                }
                                if (ficInternos[i].indexOf(nameFileWinrar) != -1) {
                                    try {
                                        File fn = new File(carpetaInterna + "\\" + ficInternos[i]);
                                        fn.delete();
                                        jTxtResultado.setText(jTxtResultado.getText() + "\n" + "Archivo Eliminado " + ficInternos[i]);
                                        System.out.println("El fichero ha sido borrado satisfactoriamente = " + ficInternos[i]);
                                    } catch (Exception errFil) {
                                        System.err.println("El fichero no puede ser borrado: " + ficInternos[i] + " ");
                                        System.err.println(errFil);
                                    }
                                }
                            }
                        }
                    }
                }
                JOptionPane.showMessageDialog(rootPane, "Se ha completado el proceso", "Proceso Terminado", JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            jTxtResultado.setText("No existen programas de descompresion (Winrar/7Zip)... Operacion Cancelada.");
        }
        

    }//GEN-LAST:event_jButton2ActionPerformed


    public boolean Verificar7Zip(){
        String tmpRuta7Zip = "C:\\Program Files\\7-Zip\\7z.exe";
        File rutaFile7Zip = new File(tmpRuta7Zip);
        if (rutaFile7Zip.exists()) {
            Ruta7Zip = tmpRuta7Zip;
            return true;
        }else{
            tmpRuta7Zip = "C:\\Program Files (x86)\\7-Zip\\7z.exe";
            rutaFile7Zip = new File(tmpRuta7Zip);
            if (rutaFile7Zip.exists()) {
                Ruta7Zip = tmpRuta7Zip;
                return true;
            }else{
                System.out.println("No se encontro el programa 7Zip instalado en el sistema...");
                jTxtResultado.setText("No se encontro el programa 7Zip instalado en el sistema...");
                return false;
            }
        }
    }

    public boolean VerificarWinRAR(){
        String tmpRutaWinRar = "C:\\Program Files\\WinRAR\\WinRAR.exe";
        File rutaFileWinrar = new File(tmpRutaWinRar);
        if (rutaFileWinrar.exists()) {
            RutaWinRar = tmpRutaWinRar;
            return true;
        }else{
            tmpRutaWinRar = "C:\\Program Files (x86)\\WinRAR\\WinRAR.exe";
            rutaFileWinrar = new File(tmpRutaWinRar);
            if (rutaFileWinrar.exists()) {
                RutaWinRar = tmpRutaWinRar;
                return true;
            }else{
                System.out.println("No se encontro el programa Winrar instalado en el sistema...");
                jTxtResultado.setText("No se encontro el programa Winrar instalado en el sistema...");
                return false;
            }
        }
    }
  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    public boolean Descompress7Zip(String Carpeta, String Archivo) {
        try {
            String comando = Ruta7Zip+" x \""+Carpeta+"\\"+Archivo+"\" -y -o\""+Carpeta+"\\\"";
            System.out.println(comando);
            Process process = Runtime.getRuntime().exec(comando); //Ejecutamos el comando para descomprimir con 7Zip

            // Obtenemos el buffer de salida de la consola.
            InputStream inputstream = process.getInputStream();
            BufferedInputStream bufferedinputstream = new BufferedInputStream(inputstream);

            //Mostramos el buffer de salida en el text
            byte[] contents = new byte[1024];
            int bytesRead=0;
            String strResultContent = null; 
            while( (bytesRead = bufferedinputstream.read(contents)) != -1){
               strResultContent = new String(contents, 0, bytesRead);
            }
            jTxtResultado.setText(jTxtResultado.getText()+"\n"+"Finalizo Archivo "+Archivo);;
            jTxtResultado.setText(jTxtResultado.getText()+"\n"+strResultContent);
            process.destroy();
            return true;
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        }
    }
    
    public boolean DescompressWinRAR(String Carpeta, String Archivo) {
        try {
            String comando = RutaWinRar+" X \""+Carpeta+"\\"+Archivo+"\" \""+Carpeta+"\\\"";
            System.out.println(comando);
            Process process = Runtime.getRuntime().exec(comando); //Ejecutamos el comando para descomprimir con Winrar

            // Obtenemos el buffer de salida de la consola.
            InputStream inputstream = process.getInputStream();
            BufferedInputStream bufferedinputstream = new BufferedInputStream(inputstream);

            //Mostramos el buffer de salida en el text
            byte[] contents = new byte[1024];
            int bytesRead=0;
            String strResultContent = null; 
            while( (bytesRead = bufferedinputstream.read(contents)) != -1){
               strResultContent = new String(contents, 0, bytesRead);
            }
            jTxtResultado.setText(jTxtResultado.getText()+"\n"+"Finalizo Archivo "+Archivo);;
            jTxtResultado.setText(jTxtResultado.getText()+"\n"+strResultContent);
            process.destroy();
            return true;
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser JFC_Carpeta;
    private javax.swing.JTextField JTF_Dir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxtResultado;
    // End of variables declaration//GEN-END:variables
}
